### ISSUE TITLE
Error in new versions (2.2.0) with nativescript-vue

### ISSUE THREAD

**Issue by dungfv** [bradmartin/nativescript-ripple#24]
I using Nativescript-Vue 2.2.2 without typescript. My project works fine with nativescript-ripple 2.1.0 althought effect in IOS not OK.
But when I update Nativescript-ripple 2.2.0 catch error message 
```
ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.android.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.android.ts(59,53)
      TS2663: Cannot find name 'android'. Did you mean the instance member 'this.android'?

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.android.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.android.ts(8,22)
      TS6053: File '/Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/node_modules/tns-platform-declarations/android.d.ts' not found.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(17,33)
      TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(17,53)
      TS2304: Cannot find name 'CAAnimationDelegate'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(18,34)
      TS2552: Cannot find name 'CAAnimationDelegate'. Did you mean 'AnimationDelegate'?

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(27,37)
      TS2304: Cannot find name 'CAAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(32,44)
      TS2304: Cannot find name 'CAAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(40,39)
      TS2304: Cannot find name 'CAAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(41,46)
      TS2304: Cannot find name 'CAAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(53,34)
      TS2304: Cannot find name 'CAAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(63,27)
      TS2304: Cannot find name 'CAAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(74,11)
      TS2304: Cannot find name 'UIView'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(121,19)
      TS2304: Cannot find name 'UIView'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(121,48)
      TS2304: Cannot find name 'CGRectMake'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(128,35)
      TS2304: Cannot find name 'CATransform3DScale'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(128,54)
      TS2304: Cannot find name 'CATransform3DIdentity'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(130,26)
      TS2304: Cannot find name 'CGPointMake'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(159,28)
      TS2304: Cannot find name 'CGPointMake'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(203,27)
      TS2304: Cannot find name 'CABasicAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(203,46)
      TS2304: Cannot find name 'CABasicAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(206,37)
      TS2304: Cannot find name 'CAMediaTimingFunction'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(206,76)
      TS2304: Cannot find name 'kCAMediaTimingFunctionEaseOut'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(212,35)
      TS2304: Cannot find name 'CATransform3DScale'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(212,54)
      TS2304: Cannot find name 'CATransform3DIdentity'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(239,26)
      TS2304: Cannot find name 'CABasicAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(239,45)
      TS2304: Cannot find name 'CABasicAnimation'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(243,33)
      TS2304: Cannot find name 'CACurrentMediaTime'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(245,36)
      TS2304: Cannot find name 'CAMediaTimingFunction'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(245,75)
      TS2304: Cannot find name 'kCAMediaTimingFunctionEaseOut'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(266,23)
      TS2304: Cannot find name 'UIView'.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ios.ts(8,22)
      TS6053: File '/Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/node_modules/tns-platform-declarations/ios.d.ts' not found.

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ts
../node_modules/nativescript-ripple/ripple.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ts(59,53)
      TS2663: Cannot find name 'android'. Did you mean the instance member 'this.android'?

ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ts
../node_modules/nativescript-ripple/ripple.ts
[tsl] ERROR in /Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/ripple.ts(8,22)
      TS6053: File '/Users/dudu/code/zeko/zeko/node_modules/nativescript-ripple/node_modules/tns-platform-declarations/android.d.ts' not found.
```
Although log errors, the functionality of the plugin still works normally

**Comment by bradmartin** [comment]
hmm looks like maybe the TS got published with the version, I'll fix it. Thanks.

**Comment by bradmartin** [comment]
Try 2.2.1 and LMK if that helps.
